//
//  Recipe.swift
//  Cozy Crumb
//
//  The centre of the data model. Everything else hangs off this.
//

import Foundation
import SwiftData

enum SourceKind: String, Codable, CaseIterable, Sendable {
    /// Imported from a recipe site via structured data or the AI parser.
    case web
    /// Imported from a social caption (Instagram, TikTok, YouTube).
    case social
    /// Typed in by hand.
    case manual
    /// Generated by the Sous Chef.
    case aiGenerated

    // nonisolated for the same reason as GroceryCategory: @Model types are
    // nonisolated and read these directly.
    nonisolated var displayName: String {
        switch self {
        case .web: "From the web"
        case .social: "From social"
        case .manual: "Added by hand"
        case .aiGenerated: "From the Sous Chef"
        }
    }

    nonisolated var symbol: String {
        switch self {
        case .web: "globe"
        case .social: "play.rectangle"
        case .manual: "pencil"
        case .aiGenerated: "sparkles"
        }
    }
}

@Model
final class Recipe {
    @Attribute(.unique) var id: UUID
    var title: String
    var summary: String?

    var sourceURL: URL?
    /// "Bon Appétit", "@user on TikTok".
    var sourceName: String?
    var sourceKind: SourceKind

    /// Downscaled to max 1200px, JPEG 0.8. Kept out of the main store file.
    @Attribute(.externalStorage) var heroImageData: Data?

    var servings: Int
    var prepMinutes: Int?
    var cookMinutes: Int?

    @Relationship(deleteRule: .cascade, inverse: \Ingredient.recipe)
    var ingredients: [Ingredient]

    @Relationship(deleteRule: .cascade, inverse: \RecipeStep.recipe)
    var steps: [RecipeStep]

    @Relationship(deleteRule: .cascade, inverse: \CookLog.recipe)
    var cookLogs: [CookLog]

    @Relationship(inverse: \RecipeCollection.recipes)
    var collections: [RecipeCollection]

    /// Cascades: a recipe you delete shouldn't leave an empty slot sitting in
    /// next week's plan.
    @Relationship(deleteRule: .cascade, inverse: \PlannedMeal.recipe)
    var plannedMeals: [PlannedMeal]

    var tags: [String]
    var isFavorite: Bool
    /// 1–5.
    var rating: Int?
    var personalNotes: String?

    /// 0–1 from the import cascade. Below 0.8 shows a "worth a quick look"
    /// banner on the review screen.
    var importConfidence: Double?

    var createdAt: Date
    var updatedAt: Date
    /// Drives the "Recently cooked" section without walking every cook log.
    var lastCookedAt: Date?

    init(
        id: UUID = UUID(),
        title: String,
        summary: String? = nil,
        sourceURL: URL? = nil,
        sourceName: String? = nil,
        sourceKind: SourceKind = .manual,
        heroImageData: Data? = nil,
        servings: Int = 4,
        prepMinutes: Int? = nil,
        cookMinutes: Int? = nil,
        ingredients: [Ingredient] = [],
        steps: [RecipeStep] = [],
        cookLogs: [CookLog] = [],
        collections: [RecipeCollection] = [],
        plannedMeals: [PlannedMeal] = [],
        tags: [String] = [],
        isFavorite: Bool = false,
        rating: Int? = nil,
        personalNotes: String? = nil,
        importConfidence: Double? = nil,
        createdAt: Date = .now,
        updatedAt: Date = .now,
        lastCookedAt: Date? = nil
    ) {
        self.id = id
        self.title = title
        self.summary = summary
        self.sourceURL = sourceURL
        self.sourceName = sourceName
        self.sourceKind = sourceKind
        self.heroImageData = heroImageData
        self.servings = servings
        self.prepMinutes = prepMinutes
        self.cookMinutes = cookMinutes
        self.ingredients = ingredients
        self.steps = steps
        self.cookLogs = cookLogs
        self.collections = collections
        self.plannedMeals = plannedMeals
        self.tags = tags
        self.isFavorite = isFavorite
        self.rating = rating
        self.personalNotes = personalNotes
        self.importConfidence = importConfidence
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastCookedAt = lastCookedAt
    }
}

// MARK: - Derived

extension Recipe {
    /// SwiftData does not preserve relationship order, so every ordered
    /// relationship is sorted through its `order` property on read.
    var orderedIngredients: [Ingredient] {
        ingredients.sorted { $0.order < $1.order }
    }

    var orderedSteps: [RecipeStep] {
        steps.sorted { $0.order < $1.order }
    }

    var orderedCookLogs: [CookLog] {
        cookLogs.sorted { $0.date > $1.date }
    }

    var totalMinutes: Int? {
        switch (prepMinutes, cookMinutes) {
        case let (prep?, cook?): prep + cook
        case let (prep?, nil): prep
        case let (nil, cook?): cook
        case (nil, nil): nil
        }
    }

    /// "1 hr 5 min", "35 min", or nil when the recipe carries no timing.
    var totalTimeDisplay: String? {
        guard let totalMinutes, totalMinutes > 0 else { return nil }
        let hours = totalMinutes / 60
        let minutes = totalMinutes % 60

        return switch (hours, minutes) {
        case (0, let m): "\(m) min"
        case (let h, 0): "\(h) hr"
        case (let h, let m): "\(h) hr \(m) min"
        }
    }

    /// Ingredients that are real items rather than "For the sauce:" headers.
    var shoppableIngredients: [Ingredient] {
        orderedIngredients.filter { !$0.isSectionHeader }
    }

    /// True when the import was shaky enough to warrant a nudge (§5.2).
    var needsReview: Bool {
        guard let importConfidence else { return false }
        return importConfidence < 0.8
    }

    func touch() {
        updatedAt = .now
    }
}
